export const projects = [
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
  {
    title: "Climb Base!",
    subtitle: "App that was created to bring climbers together!",
    description: "See above",
    image: "",
    link: "www.google.com",
  },
];
